name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Remote Deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/quantic_final_project-main
          # Stash any local changes if present
          git stash
          # Fetch and reset to ensure exact match with remote main
          git fetch origin main
          git reset --hard origin/main
          
          # Redeploy all containers
          bash deploy/launch.sh
